spbd/src/main/java/com/spbd/cashflow/spring/model/Diary.java
package com.spbd.cashflow.spring.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(name="Diary")
public class Diary implements Serializable {
	
	@Id
	@GeneratedValue
	@Column(name="id", unique = true)
	private long id;
	
	@Column(name="month_nr")
	private int monthNumber;
	
	@Column(name="business_in")
	private double businessIn;
	
	@Column(name="business_out")
	private double businessOut;
	
	@Column(name="household_in")
	private double householdIn;
	
	@Column(name="household_out")
	private double householdOut;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getMonthNumber() {
		return monthNumber;
	}

	public void setMonthNumber(int monthNumber) {
		this.monthNumber = monthNumber;
	}

	public double getBusinessIn() {
		return businessIn;
	}

	public void setBusinessIn(double businessIn) {
		this.businessIn = businessIn;
	}

	public double getBusinessOut() {
		return businessOut;
	}

	public void setBusinessOut(double businessOut) {
		this.businessOut = businessOut;
	}

	public double getHouseholdIn() {
		return householdIn;
	}

	public void setHouseholdIn(double householdIn) {
		this.householdIn = householdIn;
	}

	public double getHouseholdOut() {
		return householdOut;
	}

	public void setHouseholdOut(double householdOut) {
		this.householdOut = householdOut;
	}
	
	public String toString() {
		return "Diary: Month nr: " + getMonthNumber();
	}
}

spbd/src/main/java/com/spbd/cashflow/spring/model/User.java
package com.spbd.cashflow.spring.model;

import java.io.Serializable;
import java.sql.Blob;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;


@Entity
@Table(name="\"User\"")
public class User implements Serializable {

	@Id
	@GeneratedValue
	@Column(name="id", unique = true)
	private long id;
	
	@ManyToMany
	@JoinTable(name="UsersAndRoles",
			joinColumns=@JoinColumn(name="id"),
			inverseJoinColumns=@JoinColumn(name="role_id"))
	private List<Role> roles;
	
	@Enumerated(EnumType.STRING)
	private UserStatus status;
	
	//@Column(name="role_id")
    //private Integer role_id;

	@Column(name="username", unique = true)
    private String username;
	
	@Column(name="password")
	private String password;
	
	@Column(name="first_name")
	private String firstName;
	
	@Column(name="last_name")
	private String lastName;
	
	@Column(name="Date_of_Bith")
	private Date dateOfBith;
	
	@Column(name="Gender")
	private String gender;
	
	@Column(name="Email_address")
	private String emailAddress;
	
	@Column(name="Mobile_number")
	private String mobileNnumber;
	
	@Column(name="Country")
	private String country;
	
	@Column(name="Address")
	private String address;
	
	@Column(name="User_picture")
	private Blob userPicture;
	

	// Relationship between User table and Applicant table  - Stop for now
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "User_Applicant", joinColumns = {
        @JoinColumn(name = "user_id")}, inverseJoinColumns = {
        @JoinColumn(name = "app_id")})
	private List<Applicant> applicants;
	
	
	public User() {
		applicants = new ArrayList<Applicant>();
	}
	
	public String getUserFullName()
	{
		if(firstName==null && lastName==null)
			return "";
		return firstName.trim()+" "+lastName.trim();
	}

	public List<Applicant> getApplicants() {
		return applicants;
	}

	public void setApplicants(List<Applicant> applicants) {
		this.applicants = applicants;
	}
	
	// Attributes Getters and Setters //
	
	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	public UserStatus getStatus() {
		return status;
	}

	public void setStatus(UserStatus status) {
		this.status = status;
	}
	
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	public Date getDateOfBith() {
		return dateOfBith;
	}

	public void setDateOfBith(Date dateOfBith) {
		this.dateOfBith = dateOfBith;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getEmailAddress() {
		return emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getMobileNnumber() {
		return mobileNnumber;
	}

	public void setMobileNnumber(String mobileNnumber) {
		this.mobileNnumber = mobileNnumber;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Blob getUserPicture() {
		return userPicture;
	}

	public void setUserPicture(Blob userPicture) {
		this.userPicture = userPicture;
	}
	
	// End of the Getters and Setters //
	

	public String toString() {
        return getFirstName() + " " + getLastName() +" ("+getUsername()+")";
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (id != other.id)
			return false;
		return true;
	}

	
}

spbd/src/main/webapp/loans/addcashflow.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="content">
			<h:form>
				<h3>Add cashflow</h3>
				<h:panelGrid columns="3" style="margin-bottom:10px" cellpadding="5">
			        <p:outputLabel id="selectApplicantMenu" value="Client: " />
			        <p:selectOneMenu required="true" id="loanOfficer" style="width:250px" value="#{addCashflowMB.applicant}" converter="#{applicantConverter}">
			            <f:selectItems value="#{applicantMB.applicantList}"/>
			        </p:selectOneMenu>
			            <br/>
			     
				 <h:outputLabel for="loanAmount" value="Loan amount: " />
				 <p:inputText id="loanAmount" required="true" requiredMessage="Please fill in the field" validatorMessage="Please select a value between 0.5 and 200000.5" value="#{addCashflowMB.loanAmount}" style="width:250px">
		                    <f:validateDoubleRange minimum="0.5" maximum="200000.5" />
		                    <p:ajax event="blur" update="loanAmountMsg" />
		        </p:inputText>
		        <p:message id="loanAmountMsg" for="loanAmount"/>
		        
		        <p:outputLabel for="dateSubmitted" value="Application date: "/>
        		<p:calendar required="true" requiredMessage="Please select a date" id="dateSubmitted" value="#{addCashflowMB.dateSubmitted}"/>
				<p:message id="dateSubmittedMsg" for="dateSubmitted"/>
				
				<!-- <p:separator/> -->
			    <p:commandButton id="addCashflow" value="Add" action="#{addCashflowMB.addCashflow}" ajax="false"/>
			    </h:panelGrid>
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

spbd/src/main/webapp/loans/budget.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="content">		
			<h:form>
				<p:panel header="Budget (average)">
				<!--  <p:messages/>-->
				<h:outputLabel value="Business" styleClass="h3"/>
				 <h:panelGrid columns="2" columnClasses="h4, value">

				 <h:outputText value="Cash inflow: " />
				 <p:inputText id="val1" value="#{budgetMB.averageBusinessCashInflow}">
		                    <f:validateDoubleRange minimum="0" maximum="200000.5" />
		                    <p:ajax event="keyup" update="val3" listener="#{budgetMB.handleBusinessKeyEvent}" />
		         </p:inputText>
		       
		         <h:outputText value="Cash outflow: " />
				 <p:inputText id="val2" value="#{budgetMB.averageBusinessCashOutflow}">
		                    <f:validateDoubleRange minimum="0" maximum="200000.5" />
		                    <p:ajax event="keyup" update="val3" listener="#{budgetMB.handleBusinessKeyEvent}" />
		         </p:inputText>
		          
		         <h:outputText value="Cash netflow: " />
				 <h:outputText id="val3" value="#{budgetMB.averageBusinessCashNetflow}" style="#{budgetMB.businessNetColor}" />

				<h:outputLabel value="Household" styleClass="h3"/>
				<h3></h3>

		         <h:outputText value="Cash inflow: " />
				 <p:inputText id="val4" value="#{budgetMB.averageHouseholdCashInflow}">
		                    <f:validateDoubleRange minimum="0" maximum="200000.5" />
		                    <p:ajax event="keyup" update="val6" listener="#{budgetMB.handleHouseholdKeyEvent}" />
		         </p:inputText>
		         
		         <h:outputText value="Cash outflow: " />
				 <p:inputText id="val5" value="#{budgetMB.averageHouseholdCashOutflow}">
		                    <f:validateDoubleRange minimum="0" maximum="200000.5" />
		                    <p:ajax event="keyup" update="val6" listener="#{budgetMB.handleHouseholdKeyEvent}" />
		         </p:inputText>
		         
		         <h:outputText value="Cash netflow: " />
				 <h:outputText id="val6" value="#{budgetMB.averageHouseholdCashNetflow}" style="#{budgetMB.householdNetColor}" />
				
			    </h:panelGrid>
			    </p:panel>
			    <p:commandButton id="addBudget" value="Next" action="#{budgetMB.addBudget}" ajax="false"/>
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

spbd/src/main/webapp/loans/diary.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="content">
			<h:form id="form">
				<h3>Diary</h3>
				
				<h:panelGrid columns="2" cellpadding="5" class="ui-grid">
        <h:outputLabel for="nrMonths" value="Number of diary entries: " />
        <p:spinner id="nrMonths" value="#{diaryMB.number1}" stepFactor="1" min="1" max="12"/>
    </h:panelGrid>
 
    <p:commandButton value="Submit" actionListener="#{diaryMB.setShowTrue}" update="table"/>
				
				
	<p:growl id="msgs" showDetail="true"/>
   
    <h:panelGroup id="table">
    <p:contextMenu for="diaries" widgetVar="cMenu">   
       <p:menuitem value="Edit Cell" icon="ui-icon-search" onclick="PF('cellDiaries').showCellEditor();return false;"/>  
       <p:menuitem value="Hide Menu" icon="ui-icon-close" onclick="PF('cMenu').hide()"/>  
   </p:contextMenu>
<p:dataTable id="diaries" rendered="#{diaryMB.show}" var="diary" value="#{diaryMB.diaries}" editable="true" editMode="cell" widgetVar="cellDiaries">
       <f:facet name="header">
           Diary entries (Cell Editing with DoubleClick and RightClick)
       </f:facet>
 
       <p:ajax event="cellEdit" listener="#{diaryMB.onCellEdit}" update=":form:msgs, :form:avgs" />
 
       <p:column headerText="Week Number">
               <h:outputText value="#{diary.monthNumber}" />
          </p:column>
          <p:column headerText="Business Cash Inflow">
                 <p:cellEditor>
               <f:facet name="output"><h:outputText value="#{diary.businessIn}" /></f:facet>
               <f:facet name="input"><p:inputText value="#{diary.businessIn}" style="width:96%"/></f:facet>
           </p:cellEditor>
       	  </p:column>
       	  
      <p:column headerText="Business Cash Outflow">
           <p:cellEditor>
               <f:facet name="output"><h:outputText value="#{diary.businessOut}" /></f:facet>
               <f:facet name="input"><p:inputText value="#{diary.businessOut}" style="width:96%"/></f:facet>
           </p:cellEditor>
       	  </p:column>
       	  
      <p:column headerText="Household Cash Inflow">
           <p:cellEditor>
               <f:facet name="output"><h:outputText value="#{diary.householdIn}" /></f:facet>
               <f:facet name="input"><p:inputText value="#{diary.householdIn}" style="width:96%"/></f:facet>
           </p:cellEditor>
       	  </p:column>
       	
      <p:column headerText="Household Cash Outflow">
           <p:cellEditor>
               <f:facet name="output"><h:outputText value="#{diary.householdOut}" /></f:facet>
               <f:facet name="input"><p:inputText value="#{diary.householdOut}" style="width:96%"/></f:facet>
           </p:cellEditor>
       	  </p:column>
       	  <f:facet name="footer">
       	    <p:commandButton id="diaryAvgs" value="Show Average Values" action="#{diaryMB.showAvgs}" update="average" ajax="false"/>
            <p:commandButton id="addDiary" value="Next" action="#{diaryMB.addDiary}" ajax="false"/>
        </f:facet>    
  </p:dataTable>
  </h:panelGroup>
  <br/>
  <h:panelGroup id="average">
  <p:dataTable id="avgs" rendered="#{diaryMB.showAvg}" var="avg" value="#{diaryMB.avgs}">
    <f:facet name="header">
           Average Diary Cash Flows
       </f:facet>
    <p:column headerText="Average Business Cash In Flow">
        <h:outputText value="#{avg.avgBusIn}" />
    </p:column>
 
    <p:column headerText="Average Business Out">
        <h:outputText value="#{avg.avgBusOut}" />
    </p:column>
 
    <p:column headerText="Average Household In">
        <h:outputText value="#{avg.avgHouseIn}" />
    </p:column>
 
    <p:column headerText="Average Household Out">
        <h:outputText value="#{avg.avgHouseOut}" />
    </p:column>
</p:dataTable>
</h:panelGroup>
  
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

spbd/src/main/webapp/loans/loanlist.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="/templates/template.xhtml">	
	 	<ui:define name="content">		
		    <h2>Cashflow list</h2>
			<h:form>
		        <p:dataTable id="cashflows" var="cashflow" value="#{loanListMB.cashflows}" style="width:100%" filteredValue="#{loanListMB.filteredCashflows}" widgetVar="cashflowTable" paginator="true" rows="20">
		            <f:facet name="header">
        				Loans
        				<p:commandButton id="toggler" type="button" style="float:right" icon="ui-icon-calculator" />
        				<p:columnToggler datasource="cashflows" trigger="toggler" />
    				</f:facet>
		            <p:column filterBy="#{cashflow.id}" headerText="ID" filterMatchMode="contains">
		                <h:outputText value="#{cashflow.id}" />
		            </p:column>
		            <p:column filterBy="#{cashflow.applicant.name}" headerText="Client Name" filterMatchMode="contains">
		                <h:outputText value="#{cashflow.applicant.name}" />
		            </p:column>
		             <p:column filterBy="#{cashflow.applicant.loanOfficer.userFullName}" headerText="Loan Officer" filterMatchMode="contains">
		                <h:outputText value="#{cashflow.applicant.loanOfficer.userFullName}" />
		            </p:column>
		            <p:column>
		                <f:facet name="header">
		                    <h:outputText value="Loan amount" />
		                </f:facet>
		                <h:outputText value="#{cashflow.loanAmount}" />
		            </p:column>
		             <p:column>
		                <f:facet name="header">
		                    <h:outputText value="Weekly Repayment" />
		                </f:facet>
		                <h:outputText value="#{cashflow.weeklyRepayment}" />
		            </p:column>
		             <p:column>
		                <f:facet name="header">
		                    <h:outputText value="Weeks to pay" />
		                </f:facet>
		                <h:outputText value="#{cashflow.weeksToPay}" />
		            </p:column>
		            <!--  <p:column>
		                <f:facet name="header">
		                    <h:outputText value="Analysis/Recomendation" />
		                </f:facet>
		                <h:outputText value="#{cashflow.summary}" />
		            </p:column> -->
		            <p:column filterBy="#{cashflow.accepted}" headerText="Loan Decision" filterMatchMode="equals">
            			<f:facet name="filter">
                			<p:selectOneMenu onchange="PF('cashflowTable').filter()">
                    			<f:converter converterId="javax.faces.Boolean" />
                    			<f:selectItem itemLabel="All" itemValue="" />
                    			<f:selectItem itemLabel="Accepted" itemValue="true" />
                    			<f:selectItem itemLabel="Rejected" itemValue="false" />
                			</p:selectOneMenu>
            			</f:facet>
            			<h:outputText value="#{cashflow.accepted ? 'Accepted': 'Rejected'}" />
        			</p:column>
		            <p:column>
		                <f:facet name="header">
		                    <h:outputText value="View Loan" />
		                </f:facet>
		                	<h:commandLink action="view">
		                		<h:graphicImage height="20" library="imgs" name="view_icon.png" />
		                		<f:param name="id" value="#{cashflow.id}" />
		                	</h:commandLink>
		            </p:column>
		        </p:dataTable>
		    </h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html> 

spbd/src/main/webapp/loans/review.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
	<ui:composition template="/templates/template.xhtml">
		<ui:define name="content">
			<h:form>				 
				<p:panelGrid style="margin-top:20px; width:75%">
				    <f:facet name="header">
				        <p:row>
				            <p:column colspan="7">Review</p:column>
				        </p:row>
				        <p:row>
				            <p:column colspan="2">Business (Diary)</p:column>
				            <p:column colspan="1">Loan amount</p:column>
				            <p:column colspan="2">Business (Budget)</p:column>
				        </p:row>
				 
				    </f:facet>
				 	
				 	<p:row>
					 	<p:column><h:outputText value="Inflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.pastBusinessIn}" /></p:column>
					 	
					 	<p:column style="font-size:200%; text-align:center;" rowspan="3"><h:outputText value="#{reviewMB.loanAmount}" /></p:column>
					 	
					 	<p:column><h:outputText value="Inflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.budgetBusinessIn}" /></p:column>
				 	</p:row>
				 	
				 	<p:row>
					 	
					 	<p:column><h:outputText value="Outflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.pastBusinessOut}" /></p:column>
					 	
					 	<p:column><h:outputText value="Outflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.budgetBusinessOut}" /></p:column>
					 
				 	</p:row>
				 	
				 	<p:row>
					 	
					 	<p:column><h:outputText value="Netflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.pastBusinessNet}" /></p:column>
					 	
					 	<p:column><h:outputText value="Netflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.budgetBusinessNet}" /></p:column>
					 
				 	</p:row>
				   
				   <p:row>
				        <p:column style="text-align:center;" colspan="2" styleClass="ui-widget-header">
				            <h:outputText value="Household (Diary)" />
				        </p:column>
				        <p:column colspan="1" styleClass="ui-widget-header">
				            <h:outputText value="" />
				        </p:column>
				        <p:column style="text-align:center;" colspan="2" styleClass="ui-widget-header">
				            <h:outputText value="Household (Budget)" />
				        </p:column>
			   		</p:row>
			   		
			   		<p:row>
					 	<p:column><h:outputText value="Inflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.pastHouseholdIn}" /></p:column>
					 	
					 	<p:column style="text-align:center;" rowspan="3"><p:commandButton value="Guidelines" type="button" onclick="PF('dlg1').show();" /></p:column>
					 	
					 	<p:column><h:outputText value="Inflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.budgetHouseholdIn}" /></p:column>
				 	</p:row>
				 	
				 	<p:row>
					 	
					 	<p:column><h:outputText value="Outflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.pastHouseholdOut}" /></p:column>
					 	
					 	<p:column><h:outputText value="Outflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.budgetHouseholdOut}" /></p:column>
					 
				 	</p:row>
				 	
				 	<p:row>
					 	
					 	<p:column><h:outputText value="Netflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.pastHouseholdNet}" /></p:column>
					 						 	
					 	<p:column><h:outputText value="Netflow: " /></p:column>
					 	<p:column><h:outputText value="#{reviewMB.budgetHouseholdNet}" /></p:column>
					 
				 	</p:row>
				 	
				 	<p:row>
					 	
					 	<p:column colspan="5"><h:outputText value="Is the cashflow realistic? " />
					 		<p:commandButton action="next" id="yes" value="Yes" ajax="false"/>
					 		<p:commandButton onclick="PF('dlg2').show();" id="no" value="No"/>
					 	</p:column>
					 
				 	</p:row>
			    
				</p:panelGrid>
				<p:dialog header="Guidelines" widgetVar="dlg1" minHeight="40" width="40%">
				    <p:dataTable id="guidelines" var="guideline" value="#{reviewMB.guidelines}" >
		            <p:column width="50%">
		                <f:facet name="header">
		                    <h:outputText value="Business Type" />
		                </f:facet>
		                <h:outputText value="#{guideline.businessType}" />
		            </p:column>
		            <p:column>
		                <f:facet name="header">
		                    <h:outputText value="Min" />
		                </f:facet>
		                <h:outputText value="#{guideline.minNetCashflow}" />
		            </p:column>
		            <p:column>
		                <f:facet name="header">
		                    <h:outputText value="Max" />
		                </f:facet>
		                <h:outputText value="#{guideline.maxNetCashflow}" />
		            </p:column>
		        	</p:dataTable>
				</p:dialog>
				
				<p:dialog header="What do you want to do?" widgetVar="dlg2" minHeight="40">
				    <p:commandButton action="addcashflow" id="startover" value="Start over" ajax="false"/>
				    <p:commandButton action="home" id="home" value="End cashflow" ajax="false"/>
				</p:dialog>
				
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>